"use client";

import React, { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import styles from "./retailnext.module.css";

interface SubFeature {
    name: string;
    code: string;
    description: string;
    highlights: string[];
    operationalPill: string;
    previewBadge: string;
    previewDetail: string;
}

interface ManagerTheme {
    accent: string;
    lightBg: string;
    border: string;
    badgeBg: string;
}

interface ManagerModule {
    id: string;
    title: string;
    shortTitle: string;
    tagline: string;
    theme: ManagerTheme;
    capabilities: string[];
    icon: React.ReactNode;
    features: SubFeature[];
}

export default function RetailNextPage() {
    const [openFaq, setOpenFaq] = useState<number | null>(0);

    const toggleFaq = (index: number) => {
        setOpenFaq(openFaq === index ? null : index);
    };

    const managersData: ManagerModule[] = [
        {
            id: "sales-manager",
            title: "Sales Manager",
            shortTitle: "Sales",
            tagline: "Track revenue streams, cashier quotas, and counter registers in real time.",
            theme: {
                accent: "#5e2b9d",
                lightBg: "#faf5ff",
                border: "#e9d5ff",
                badgeBg: "#f3e8ff",
            },
            capabilities: ["Multi-Tender Payments", "GST & Margin Ledgers", "Shift X/Z Audits", "Cashier Attribution"],
            icon: (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="18" y1="20" x2="18" y2="10" />
                    <line x1="12" y1="20" x2="12" y2="4" />
                    <line x1="6" y1="20" x2="6" y2="14" />
                </svg>
            ),
            features: [
                {
                    name: "Sales",
                    code: "SALES-01",
                    description: "Complete sales journal capturing every billed transaction across all retail outlets. Monitor real-time gross totals, net profit margins, taxes, and payment mode breakdowns.",
                    highlights: [
                        "Real-time transaction log & invoice reprints",
                        "Cash, UPI, Credit Card, and Store Credit breakdown",
                        "Tax (GST) summaries & margin computations",
                        "Instant export to Excel and PDF formats"
                    ],
                    operationalPill: "⚡ Live Ledger Sync",
                    previewBadge: "INV #RN-4892 • ₹3,850 • Cash + UPI",
                    previewDetail: "Real-time ledger audit active. Tax: 18% GST auto-computed, zero reconciliation mismatch."
                },
                {
                    name: "Employee Sales",
                    code: "SALES-02",
                    description: "Granular attribution of revenue generated by individual sales associates and counter cashiers. Measure employee contribution, targets, and sales commission incentives.",
                    highlights: [
                        "Individual staff sales targets & achievements",
                        "Automated commission calculation rules",
                        "Leaderboards to motivate peak counter performance",
                        "Audit cashier-level item discounts and overrides"
                    ],
                    operationalPill: "🎯 Commission Attribution",
                    previewBadge: "Cashier Rahul • Target: 114% Achieved",
                    previewDetail: "Attributed ₹84,200 today across 42 orders. Incentive commission computed: ₹2,100."
                },
                {
                    name: "Counter Sales",
                    code: "SALES-03",
                    description: "End-to-end POS counter register reconciliation. Manage shift openings, cash drawer till floats, midday cash drops, and end-of-day X/Z shift closure reports.",
                    highlights: [
                        "Shift opening & closing float declarations",
                        "Physical drawer vs system cash discrepancy alerts",
                        "Detailed X-Report & Z-Report generation",
                        "Multi-counter load distribution tracking"
                    ],
                    operationalPill: "🧾 Shift X/Z Reconciliation",
                    previewBadge: "Counter #02 • Till Float: ₹5,000 Verified",
                    previewDetail: "Shift closing Z-Report ready. Cash drawer physical balance matches system total precisely."
                }
            ]
        },
        {
            id: "product-manager",
            title: "Product Manager",
            shortTitle: "Products",
            tagline: "Centralized catalog management with variations, barcode printing, and pricing tiers.",
            theme: {
                accent: "#0284c7",
                lightBg: "#f0f9ff",
                border: "#bae6fd",
                badgeBg: "#e0f2fe",
            },
            capabilities: ["Multi-Level Categories", "Size × Color Matrix", "Thermal Barcode Roll", "HSN/SAC Masters"],
            icon: (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
                    <polyline points="3.27 6.96 12 12.01 20.73 6.96" />
                    <line x1="12" y1="22.08" x2="12" y2="12" />
                </svg>
            ),
            features: [
                {
                    name: "Categories",
                    code: "PROD-01",
                    description: "Structured multi-level categorization tree for departments, sub-categories, and brands. Enforces automated GST tax slab rules and quick-filter buttons on POS screens.",
                    highlights: [
                        "Parent-child category hierarchies",
                        "Tax slabs & HSN mappings at category level",
                        "POS quick-touch tile groupings",
                        "Departmental sales margin reporting"
                    ],
                    operationalPill: "📂 Departmental Tax Slabs",
                    previewBadge: "Apparel > Men's > Casual Shirts (12% GST)",
                    previewDetail: "HSN code 6205 automatically assigned. Quick-tile button active on POS Counter 1 & 2."
                },
                {
                    name: "Variations",
                    code: "PROD-02",
                    description: "Advanced variation matrix manager for retail products with diverse sizes, colors, fabric types, weights, and bundle options under a single master parent product.",
                    highlights: [
                        "Size, color, weight, and style matrix builder",
                        "Independent SKU & Barcode per variant",
                        "Differential pricing per size or edition",
                        "Variant-level inventory allocation"
                    ],
                    operationalPill: "🎨 Matrix Variations",
                    previewBadge: "Sizes [S, M, L, XL] × Colors [Navy, Olive]",
                    previewDetail: "8 distinct variant SKUs auto-generated with dedicated barcodes & unified cost margins."
                },
                {
                    name: "Products",
                    code: "PROD-03",
                    description: "Universal master catalog of all retail items. Configure SKU codes, item descriptions, purchase costs, MRP, wholesale rate, batch settings, and reorder limits.",
                    highlights: [
                        "Unified SKU, HSN/SAC code, and brand data",
                        "Cost price vs MRP margin configuration",
                        "Minimum reorder alert threshold settings",
                        "Bulk product import/export via CSV templates"
                    ],
                    operationalPill: "📦 Unified Catalog Master",
                    previewBadge: "SKU: RN-APP-9201 • Margin: 38.5%",
                    previewDetail: "Cost: ₹620 • MRP: ₹1,299 • Reorder Trigger: 25 units across 3 outlets."
                },
                {
                    name: "Barcode Generator",
                    code: "PROD-04",
                    description: "Integrated in-house barcode and QR label generator. Design custom sticker layouts with product name, price, expiry, and batch number, then print directly to thermal label rolls.",
                    highlights: [
                        "Supports EAN-13, Code-128, and QR Code formats",
                        "Customizable label dimensions (single & multi-column)",
                        "One-click batch sticker printing for new inwards",
                        "Seamless compatibility with Zebra, TSC, and TVS printers"
                    ],
                    operationalPill: "🏷️ Thermal Direct Print",
                    previewBadge: "EAN-13: 890412891204 • Batch #B-902",
                    previewDetail: "50×25mm thermal label roll design verified. Direct print ready via USB/LAN thermal printers."
                }
            ]
        },
        {
            id: "return-exchange-manager",
            title: "Return & Exchange Manager",
            shortTitle: "Returns",
            tagline: "Hassle-free counter returns, condition verification, and automated customer refunds.",
            theme: {
                accent: "#ea580c",
                lightBg: "#fff7ed",
                border: "#fed7aa",
                badgeBg: "#ffedd5",
            },
            capabilities: ["Instant Invoice Lookup", "Credit Notes", "Size/Item Swap", "Condition Audit"],
            icon: (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="1 4 1 10 7 10" />
                    <polyline points="23 20 23 14 17 14" />
                    <path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 0 1 3.51 15" />
                </svg>
            ),
            features: [
                {
                    name: "Returns",
                    code: "RET-01",
                    description: "Lightning-fast return handling at the checkout counter. Lookup past bills by invoice number or mobile, verify purchase eligibility, and issue cash refunds or store credits.",
                    highlights: [
                        "Scan invoice barcode to pull complete bill data",
                        "Item condition audit (resellable vs damaged/defective)",
                        "Issue Store Credit Notes or direct cash/UPI refunds",
                        "Strict supervisor override approvals for safety"
                    ],
                    operationalPill: "🔁 Credit Note Issuance",
                    previewBadge: "Return Inv #RN-3108 • Credit Note Issued",
                    previewDetail: "Store Credit of ₹1,499 assigned to customer mobile. Zero cash drain from till."
                },
                {
                    name: "Exchanges",
                    code: "RET-02",
                    description: "Process in-line product exchanges in a single transaction. Swap sizes, colors, or switch to a different product while instantly computing price adjustments.",
                    highlights: [
                        "Single-receipt swap (Return item + New purchase)",
                        "Instant debit or credit balance reconciliation",
                        "Zero manual calculation errors for counter clerks",
                        "Automatic inventory replenishment for good returns"
                    ],
                    operationalPill: "🔄 Single-Receipt Swap",
                    previewBadge: "Exchange: Size M -> Size L (+₹150 diff)",
                    previewDetail: "Returned item restocked into inventory; price differential collected via UPI."
                }
            ]
        },
        {
            id: "stock-manager",
            title: "Stock Manager",
            shortTitle: "Stock",
            tagline: "Complete multi-warehouse inventory control, batch-tracking, and inter-store stock transfers.",
            theme: {
                accent: "#059669",
                lightBg: "#f0fdf4",
                border: "#bbf7d0",
                badgeBg: "#dcfce7",
            },
            capabilities: ["Rack & Bin Storage", "FIFO Valuation", "Inter-Store Transfers", "Expiry Guard"],
            icon: (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="2" y="7" width="20" height="14" rx="2" ry="2" />
                    <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
                </svg>
            ),
            features: [
                {
                    name: "Warehouse",
                    code: "STK-01",
                    description: "Manage central warehousing, regional distribution hubs, and backroom storage. Define rack, aisle, and bin locations for optimized product pick-and-pack operations.",
                    highlights: [
                        "Multi-warehouse storage location hierarchy",
                        "Rack, shelf, and bin location tagging",
                        "Goods Received Notes (GRN) inward workflows",
                        "Damaged / expired quarantine inventory zones"
                    ],
                    operationalPill: "🏭 Multi-Depot Bin Allocations",
                    previewBadge: "Main Depot • Aisle 4 • Shelf B • Bin 12",
                    previewDetail: "Pallet #PL-89 inwards confirmed. 450 units routed to designated picking rack."
                },
                {
                    name: "Stock",
                    code: "STK-02",
                    description: "Live real-time visibility into quantities on hand, reserved orders, and inventory in-transit. Automated FIFO batch evaluation, expiry alerts, and stock adjustments.",
                    highlights: [
                        "Live stock counts synchronized across all stores",
                        "Batch number & expiration date tracking",
                        "Physical stock audit & cycle counting tools",
                        "Automated low-stock reorder triggers"
                    ],
                    operationalPill: "📊 Real-Time FIFO Engine",
                    previewBadge: "Available: 840 pcs • Exp: March 2027",
                    previewDetail: "FIFO rotation enforced. Low-stock trigger warning dispatched for 2 stores."
                },
                {
                    name: "Stock Transfers",
                    code: "STK-03",
                    description: "Orchestrate internal stock transfer orders (STO) between warehouses and retail stores or across store branches. Track transit milestones and verify received quantities.",
                    highlights: [
                        "Store-to-Store and Warehouse-to-Store requests",
                        "Dispatch, in-transit, and receiving status states",
                        "Discrepancy and damaged in-transit loss reporting",
                        "One-click receiving with barcode scanning validation"
                    ],
                    operationalPill: "🚚 Transit STO Validation",
                    previewBadge: "STO #TR-5401: Warehouse -> Store #03",
                    previewDetail: "In-Transit (Dispatched 11:30 AM). Receiving verification pending barcode scan."
                }
            ]
        },
        {
            id: "customer-manager",
            title: "Customer Manager",
            shortTitle: "Customers",
            tagline: "Comprehensive customer relationship management, loyalty rewards, and credit ledger.",
            theme: {
                accent: "#e11d48",
                lightBg: "#fff1f2",
                border: "#fecdd3",
                badgeBg: "#ffe4e6",
            },
            capabilities: ["Loyalty Points Tiers", "B2B GSTIN Registry", "Outstanding Due Ledger", "Preference Logs"],
            icon: (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" />
                    <circle cx="9" cy="7" r="4" />
                    <path d="M23 21v-2a4 4 0 0 0-3-3.87" />
                    <path d="M16 3.13a4 4 0 0 1 0 7.75" />
                </svg>
            ),
            features: [
                {
                    name: "Customer",
                    code: "CRM-01",
                    description: "Master directory of retail shoppers and wholesale B2B clients. Group customers into membership tiers, analyze purchase behavior, and track store credit accounts.",
                    highlights: [
                        "Centralized contact database with GSTIN support for B2B",
                        "Loyalty points accumulation and redemption engine",
                        "Credit balance limit setting & payment dues reminders",
                        "Export customer segments for targeted SMS campaigns"
                    ],
                    operationalPill: "⭐ Loyalty Tier Management",
                    previewBadge: "VIP Gold Tier • 1,240 Loyalty Points",
                    previewDetail: "Points redeemable at counter (Worth ₹620). Lifetime customer spend: ₹48,900."
                },
                {
                    name: "Individual Customer",
                    code: "CRM-02",
                    description: "360-degree customer profile view. Review chronological purchase timelines, average basket size, favorite categories, pending dues, and customized notes.",
                    highlights: [
                        "Complete itemized purchase history per customer",
                        "Outstanding credit balance ledger with payment history",
                        "Special discounts and exclusive custom pricing",
                        "Birthday, anniversary, and preference alerts"
                    ],
                    operationalPill: "👤 360° Shopper Dossier",
                    previewBadge: "Customer: Ananya M. • Avg. Basket: ₹2,150",
                    previewDetail: "Top Category: Ethnic Wear • Credit Outstanding: ₹0.00 • Last Visited: Yesterday."
                }
            ]
        },
        {
            id: "discount-manager",
            title: "Discount Manager",
            shortTitle: "Discounts",
            tagline: "Dynamic promotional coupon engine, order discounts, and targeted customer perks.",
            theme: {
                accent: "#9333ea",
                lightBg: "#fdf4ff",
                border: "#f5d0fe",
                badgeBg: "#fae8ff",
            },
            capabilities: ["Cart-Level Vouchers", "BOGO Combos", "Targeted VIP Codes", "Margin Protection"],
            icon: (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="19" y1="5" x2="5" y2="19" />
                    <circle cx="6.5" cy="6.5" r="2.5" />
                    <circle cx="17.5" cy="17.5" r="2.5" />
                </svg>
            ),
            features: [
                {
                    name: "Order Coupons",
                    code: "DISC-01",
                    description: "Create cart-level promotional coupons for festive sales, minimum spending tiers, and flat or percentage reductions applied seamlessly at checkout.",
                    highlights: [
                        "Minimum cart value prerequisites and caps",
                        "Flat currency discount or percentage discount rules",
                        "Validity period scheduling with auto-expiry",
                        "Usage limits per coupon code"
                    ],
                    operationalPill: "🎟️ Cart Promo Schemes",
                    previewBadge: "Coupon: FESTIVE20 (Min Cart: ₹2,000)",
                    previewDetail: "Auto-applies 20% discount (capped at ₹500). Active until Sunday midnight."
                },
                {
                    name: "Product Coupons",
                    code: "DISC-02",
                    description: "Run targeted promotional pricing on specific items, brands, or seasonal merchandise. Ideal for flash clearances, slow-moving items, or brand partnerships.",
                    highlights: [
                        "Category-wide and SKU-specific discount rules",
                        "Buy-One-Get-One (BOGO) combo deal support",
                        "Automatic discount deduction upon barcode scan",
                        "Margin-protection rules preventing negative margins"
                    ],
                    operationalPill: "🛍️ BOGO & Clearance Combos",
                    previewBadge: "Buy 2 Get 1 Free • Summer Linen SKU",
                    previewDetail: "Discount applies to lowest-priced item instantly when scanned at the till."
                },
                {
                    name: "Customer Coupons",
                    code: "DISC-03",
                    description: "Personalized vouchers tailored for individual VIP patrons, first-time shoppers, or win-back campaigns to re-engage inactive customers.",
                    highlights: [
                        "Unique single-use promo codes assigned to phones",
                        "Customer birthday & milestone rewards",
                        "Exclusive VIP customer tier promotions",
                        "Redemption tracking and conversion analytics"
                    ],
                    operationalPill: "🎁 Personalized VIP Perks",
                    previewBadge: "Birthday Voucher #BDAY-500 • Single-Use",
                    previewDetail: "Linked to mobile 98765***** with automated WhatsApp delivery on customer birthday."
                }
            ]
        },
        {
            id: "vendors-manager",
            title: "Vendors Manager",
            shortTitle: "Vendors",
            tagline: "Supplier lifecycle management, automated Purchase Orders, invoice 3-way matching, and dues.",
            theme: {
                accent: "#0d9488",
                lightBg: "#f0fdfa",
                border: "#99f6e4",
                badgeBg: "#ccfbf1",
            },
            capabilities: ["Supplier Profiles", "Auto-Generated POs", "3-Way GRN Match", "Accounts Payable Aging"],
            icon: (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="4" y="2" width="16" height="20" rx="2" ry="2" />
                    <line x1="9" y1="22" x2="9" y2="2" />
                    <path d="M8 6h.01" />
                    <path d="M16 6h.01" />
                    <path d="M8 10h.01" />
                    <path d="M16 10h.01" />
                    <path d="M8 14h.01" />
                    <path d="M16 14h.01" />
                    <path d="M8 18h.01" />
                    <path d="M16 18h.01" />
                </svg>
            ),
            features: [
                {
                    name: "Vendors",
                    code: "VEN-01",
                    description: "Comprehensive vendor database recording business names, contact persons, tax registration (GSTIN), credit terms, bank details, and lead procurement times.",
                    highlights: [
                        "Supplier contact & compliance registry",
                        "Credit terms & credit period (30/60/90 days) tracking",
                        "Vendor ratings and fulfillment speed metrics",
                        "Catalog pricing agreements and negotiated rates"
                    ],
                    operationalPill: "🏢 Supplier KYC & Terms",
                    previewBadge: "Apex Textiles Ltd • GSTIN: 27AAAAA0000A1Z5",
                    previewDetail: "Payment Terms: Net 45 Days • Rating: 4.9/5 • Lead Time: 3 Business Days."
                },
                {
                    name: "Vendors Orders",
                    code: "VEN-02",
                    description: "End-to-end Purchase Order (PO) creation, automated order email dispatch, expected delivery scheduling, and supplier confirmation tracking.",
                    highlights: [
                        "Auto-generate PO from low-stock thresholds",
                        "Multi-level manager approval workflow",
                        "Tracking partial deliveries and pending shipments",
                        "Direct PDF PO generation for instant dispatch"
                    ],
                    operationalPill: "📋 Auto Purchase Orders",
                    previewBadge: "PO #PO-982 • ₹1,42,000 • Approved",
                    previewDetail: "Triggered automatically from low inventory alarm. Expected delivery: Tuesday."
                },
                {
                    name: "Vendors Invoices",
                    code: "VEN-03",
                    description: "Inward purchase bill logging with 3-way reconciliation (PO vs GRN Inward vs Vendor Bill). Accurately claim input tax credits and record landed freight costs.",
                    highlights: [
                        "3-way matching preventing supplier overbilling",
                        "Input Tax Credit (ITC) categorization",
                        "Landed cost calculation incorporating shipping & customs",
                        "Direct inventory auto-inward upon invoice approval"
                    ],
                    operationalPill: "🛡️ 3-Way Reconciliation",
                    previewBadge: "Inward Bill #V-8819 • 3-Way Matched",
                    previewDetail: "PO #PO-982 vs GRN #41 vs Bill matched. Stock auto-credited into warehouse depot."
                },
                {
                    name: "Vendors Due",
                    code: "VEN-04",
                    description: "Accounts payable ledger providing real-time visibility into supplier outstanding payments, upcoming due dates, aging analysis, and partial settlements.",
                    highlights: [
                        "Payables aging schedule (0-30, 31-60, 60+ days)",
                        "Due date alert notifications avoiding late penalties",
                        "Cheque, NEFT/RTGS, and UPI settlement tracking",
                        "Consolidated vendor statement generation"
                    ],
                    operationalPill: "💳 Payables Aging Control",
                    previewBadge: "Outstanding: ₹85,000 • Due in 12 Days",
                    previewDetail: "Aging: 0-30 days bracket. Reminder scheduled before discount forfeit window."
                }
            ]
        },
        {
            id: "staff-manager",
            title: "Staff Manager",
            shortTitle: "Staff",
            tagline: "Role-based access control, cashier permission security, and sensitive operational guards.",
            theme: {
                accent: "#4f46e5",
                lightBg: "#eef2ff",
                border: "#c7d2fe",
                badgeBg: "#e0e7ff",
            },
            capabilities: ["RBAC Permission Matrix", "Supervisor PIN Guard", "Margin Visibility Lock", "Action Audit Logs"],
            icon: (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                    <circle cx="12" cy="7" r="4" />
                </svg>
            ),
            features: [
                {
                    name: "Staff",
                    code: "STF-01",
                    description: "Define staff roles and permissions with fine-grained security. Prevent unauthorized billing discounts, prohibit arbitrary price overrides, and protect sensitive financial reports.",
                    highlights: [
                        "Role-based permission sets (Cashier, Supervisor, Manager)",
                        "Passcode requirements for bill cancellation & refunds",
                        "Restrict access to profit margins and wholesale purchase rates",
                        "Detailed chronological audit logs of sensitive operations"
                    ],
                    operationalPill: "🔒 High-Security RBAC",
                    previewBadge: "Role: Counter Cashier (Strict Guard)",
                    previewDetail: "Purchase costs hidden; bill deletions and item discounts require Supervisor PIN."
                }
            ]
        },
        {
            id: "employee-manager",
            title: "Employee Manager",
            shortTitle: "Employee HR",
            tagline: "Integrated HR management, shift attendance, payroll processing, ID cards, and salary advances.",
            theme: {
                accent: "#d97706",
                lightBg: "#fffbeb",
                border: "#fde68a",
                badgeBg: "#fef3c7",
            },
            capabilities: ["Biometric Shifts", "Automated Payroll", "1-Click ID Cards", "Advance Loans"],
            icon: (
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                    <circle cx="11" cy="7" r="4" />
                    <polyline points="16 11 18 13 22 9" />
                </svg>
            ),
            features: [
                {
                    name: "Employees",
                    code: "HR-01",
                    description: "Complete employee master directory holding personal identification, KYC documents, designated roles, emergency contacts, and assigned retail branch locations.",
                    highlights: [
                        "Comprehensive employee master profiles & documents",
                        "Branch assignment & shift roster allocation",
                        "Employment contracts & document uploads",
                        "Emergency contact registry"
                    ],
                    operationalPill: "👥 Master HR Directory",
                    previewBadge: "Staff ID: #DN-EMP-042 • Branch #01",
                    previewDetail: "Aadhaar & PAN KYC verified. Allocated to Morning Floor Shift (09:00 - 18:00)."
                },
                {
                    name: "Employee Attendance",
                    code: "HR-02",
                    description: "Daily shift punch clocking with biometric terminal or PIN entry integration. Tracks punctual clock-ins, lunch breaks, overtime hours, and half-day calculations.",
                    highlights: [
                        "Biometric, RFID, or PIN-based counter clock-in",
                        "Overtime and late-punch calculation rules",
                        "Monthly attendance percentage overview",
                        "Shift swap requests and approvals"
                    ],
                    operationalPill: "⏱️ Biometric Clock-in",
                    previewBadge: "Punch-In: 08:58 AM (On Time)",
                    previewDetail: "Shift logged: 8 hrs 15 mins. Overtime: 15 mins automatically credited to payroll."
                },
                {
                    name: "Payroll",
                    code: "HR-03",
                    description: "Automated monthly wage processing incorporating basic salary, attendance deductions, overtime pay, sales commissions, and statutory deductions.",
                    highlights: [
                        "One-click monthly salary sheet calculation",
                        "Automated inclusion of sales target commissions",
                        "Deduction for unpaid leaves and advances",
                        "Printable & downloadable digital payslips"
                    ],
                    operationalPill: "💰 Automated Wages",
                    previewBadge: "Net Salary: ₹28,400 • Commission: +₹2,100",
                    previewDetail: "Advance deduction: -₹2,000 linked. Payslip ready for download and WhatsApp delivery."
                },
                {
                    name: "Id Cards",
                    code: "HR-04",
                    description: "Generate and print professional employee identity cards featuring store branding, staff portrait photo, employee ID, and quick-login barcode or QR code.",
                    highlights: [
                        "Branded printable ID card templates",
                        "Quick-scan barcode for instant POS till logins",
                        "Staff security badges with role designations",
                        "Single-click batch printing"
                    ],
                    operationalPill: "🪪 Barcoded Staff Badges",
                    previewBadge: "Quick-Login QR • Store Cashier Badge",
                    previewDetail: "Print-ready CMYK format with high-resolution photo and POS login QR code."
                },
                {
                    name: "Employee leaves",
                    code: "HR-05",
                    description: "Structured leave management system with policy balances (Casual Leave, Sick Leave, Paid Time Off). Staff can apply for leave with quick manager approval workflows.",
                    highlights: [
                        "Leave quota configuration per employee type",
                        "Leave request submission & approval notifications",
                        "Real-time available leave balance ledger",
                        "Direct synchronization with monthly payroll computations"
                    ],
                    operationalPill: "📅 Leave Quota Balances",
                    previewBadge: "Leave Balance: 4 CL • 2 SL Available",
                    previewDetail: "Leave request for Friday approved by Store Supervisor. Synced to attendance roster."
                },
                {
                    name: "Employee Advances",
                    code: "HR-06",
                    description: "Record and manage employee salary advance loans. Configure monthly deduction installments that automatically link into monthly payroll generation.",
                    highlights: [
                        "Formal advance request recording and approvals",
                        "Custom installment repayment schedules",
                        "Automatic monthly payroll deduction linking",
                        "Remaining balance audit trail"
                    ],
                    operationalPill: "💸 Advance Repayments",
                    previewBadge: "Advance Loan: ₹10,000 • 5 Installments",
                    previewDetail: "Installment #2 of 5 (₹2,000) scheduled for deduction on upcoming month-end payroll."
                }
            ]
        }
    ];

    const faqs = [
        {
            q: "Can RetailNext run across multiple retail branch stores simultaneously?",
            a: "Yes! RetailNext is architected from the ground up for multi-store chains. You can manage central inventory in a master warehouse, transfer stock between branch stores, and view centralized sales performance in real time from any device."
        },
        {
            q: "How does RetailNext handle high-traffic billing counters during peak hours?",
            a: "RetailNext features high-speed keyboard shortcuts, instant barcode scanning, hold-and-recall cart capabilities, and multi-tender split payments (Cash + UPI + Card) to ensure customer checkout takes less than 5 seconds per transaction."
        },
        {
            q: "Can I print customized barcode stickers for products without manufacturer barcodes?",
            a: "Absolutely. The built-in Barcode Generator allows you to design custom label layouts (incorporating your shop name, product name, MRP, selling price, and expiry date) and batch-print them directly onto thermal sticker rolls."
        },
        {
            q: "How are employee commissions and cashier registers audited?",
            a: "The Sales Manager and Employee Manager modules collaborate seamlessly. Every bill tracks the serving staff member, automatically calculating earned commissions, while Counter Sales reconciles physical cash drawer balances against system totals at shift close."
        },
        {
            q: "Does RetailNext offer role-based access control for cashiers vs store managers?",
            a: "Yes. The Staff Manager provides granular permission toggles. Cashiers can be restricted from viewing purchase costs, profit margins, or executing bill cancellations without a supervisor PIN override."
        }
    ];

    return (
        <main className={styles.pageWrapper}>
            {/* 1. HERO SECTION */}
            <section className={styles.heroSection}>
                <div className={styles.container}>
                    <div className={styles.heroGrid}>
                        <div className={styles.heroContent}>
                            <span className={styles.badge}>RETAIL ERP &amp; POS SUITE</span>
                            <h1 className={styles.title}>
                                Modern Retail OS <br />
                                Built for <span className={styles.highlightText}>Speed &amp; Scale</span>
                            </h1>
                            <p className={styles.description}>
                                The complete cloud-ready retail operating system. From high-speed barcode checkout
                                and multi-warehouse stock replenishment to staff payroll and vendor management —
                                everything you need to run your retail chain flawlessly.
                            </p>

                            <div className={styles.ctaGroup}>
                                <Link href="/contact" className={styles.primaryBtn}>
                                    Book a Live Demo
                                    <svg width="15" height="15" viewBox="0 0 16 16" fill="none">
                                        <path d="M6 3L11 8L6 13" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                </Link>
                                <a href="#managers-suite" className={styles.secondaryBtn}>
                                    Explore All Modules
                                    <svg width="15" height="15" viewBox="0 0 16 16" fill="none">
                                        <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                </a>
                            </div>

                            <div className={styles.statsBar}>
                                <div className={styles.statItem}>
                                    <span className={styles.statValue}>&lt; 5s</span>
                                    <span className={styles.statLabel}>Billing Speed</span>
                                </div>
                                <div className={styles.statItem}>
                                    <span className={styles.statValue}>100%</span>
                                    <span className={styles.statLabel}>Stock Accuracy</span>
                                </div>
                                <div className={styles.statItem}>
                                    <span className={styles.statValue}>Multi-Store</span>
                                    <span className={styles.statLabel}>Chain Ready</span>
                                </div>
                                <div className={styles.statItem}>
                                    <span className={styles.statValue}>All-in-One</span>
                                    <span className={styles.statLabel}>POS + HR + ERP</span>
                                </div>
                            </div>
                        </div>

                        <div className={styles.heroVisualWrapper}>
                            <Image
                                src="/retail.png"
                                alt="RetailNext POS Billing and Supermarket Terminal"
                                width={680}
                                height={440}
                                className={styles.heroImage}
                                priority
                            />
                            <div className={styles.floatingTag}>
                                <span className={styles.liveDot} />
                                <span>Real-time POS &amp; Inventory Cloud Sync</span>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* 2. OPERATIONAL PILLARS (Top Highlights) */}
            <section className={styles.pillarsSection}>
                <div className={styles.container}>
                    <div className={styles.sectionHeader}>
                        <span className={styles.sectionBadge}>CORE PILLARS</span>
                        <h2 className={styles.sectionTitle}>Built for High-Velocity Retail Operations</h2>
                        <p className={styles.sectionSubtitle}>
                            Three interconnected pillars that keep your checkout counters moving fast,
                            your shelves stocked, and your management in total command.
                        </p>
                    </div>

                    <div className={styles.pillarsGrid}>
                        {/* Pillar 1: POS Billing */}
                        <div className={styles.pillarCard}>
                            <div className={styles.pillarIconWrap}>
                                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <rect x="2" y="3" width="20" height="14" rx="2" ry="2" />
                                    <line x1="8" y1="21" x2="16" y2="21" />
                                    <line x1="12" y1="17" x2="12" y2="21" />
                                </svg>
                            </div>
                            <h3 className={styles.pillarTitle}>High-Speed POS Billing</h3>
                            <p className={styles.pillarDesc}>
                                Lightning checkout designed for peak rushes with keyboard shortcuts, instant barcode lookup, and split payments.
                            </p>
                            <ul className={styles.pillarFeatureList}>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Barcode, QR &amp; touch item selection</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Hold &amp; recall carts without line delays</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Multi-tender payments: Cash, UPI, Card, Credit</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Thermal receipt and WhatsApp invoice sharing</span>
                                </li>
                            </ul>
                        </div>

                        {/* Pillar 2: Real-time Dashboard */}
                        <div className={styles.pillarCard}>
                            <div className={styles.pillarIconWrap}>
                                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <rect x="3" y="3" width="7" height="9" />
                                    <rect x="14" y="3" width="7" height="5" />
                                    <rect x="14" y="12" width="7" height="9" />
                                    <rect x="3" y="16" width="7" height="5" />
                                </svg>
                            </div>
                            <h3 className={styles.pillarTitle}>Real-Time Executive Dashboard</h3>
                            <p className={styles.pillarDesc}>
                                Live operational intelligence. Track daily turnover, margins, hourly footfall, and low-inventory alerts.
                            </p>
                            <ul className={styles.pillarFeatureList}>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Today’s gross sales, tax &amp; net margins</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Top-selling SKU velocity &amp; category trends</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Automated low stock and expiry warnings</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Mobile manager dashboard on any device</span>
                                </li>
                            </ul>
                        </div>

                        {/* Pillar 3: Multi-Store Control */}
                        <div className={styles.pillarCard}>
                            <div className={styles.pillarIconWrap}>
                                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
                                    <polyline points="9 22 9 12 15 12 15 22" />
                                </svg>
                            </div>
                            <h3 className={styles.pillarTitle}>Multi-Store Network (Stores)</h3>
                            <p className={styles.pillarDesc}>
                                Unify all physical stores, outlet counters, and depots under a central cloud control room with zero sync latency.
                            </p>
                            <ul className={styles.pillarFeatureList}>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Multi-branch master inventory synchronization</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Outlet-specific pricing and promotional slabs</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Inter-store stock transfer management</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Consolidated multi-branch P&amp;L reporting</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </section>

            {/* 3. MANAGER-WISE FEATURE SUITE (Sequential Stack: Manager Below Manager) */}
            <section className={styles.managersSection} id="managers-suite">
                <div className={styles.container}>
                    <div className={styles.managersHeader}>
                        <div className={styles.sectionBadgeGlow}>
                            <span className={styles.glowDot} />
                            <span>COMPLETE SYSTEM ARCHITECTURE</span>
                        </div>
                        <h2 className={styles.sectionTitle}>Manager-Wise Module Deep Dive</h2>
                        <p className={styles.sectionSubtitle}>
                            Explore how each specialized manager module inside RetailNext automates your store operations
                            from front checkout to backend supply chain, inventory, and staff management.
                        </p>
                    </div>

                    {/* Quick Anchor Jump Bar with Color Accents */}
                    <div className={styles.quickNavWrapper}>
                        <div className={styles.quickNavTitle}>
                            <span>Jump to Manager Module</span>
                            <span>9 Modules Available</span>
                        </div>
                        <div className={styles.quickNavList}>
                            {managersData.map((mgr) => (
                                <a key={mgr.id} href={`#${mgr.id}`} className={styles.quickNavBtn}>
                                    <span className={styles.quickNavDot} style={{ backgroundColor: mgr.theme.accent }} />
                                    <span>{mgr.title}</span>
                                </a>
                            ))}
                        </div>
                    </div>

                    {/* Sequential Stack of Managers */}
                    <div className={styles.managersStack}>
                        {managersData.map((mgr, mIndex) => (
                            <div
                                key={mgr.id}
                                id={mgr.id}
                                className={styles.managerBlock}
                                style={
                                    {
                                        "--theme-accent": mgr.theme.accent,
                                        "--theme-light-bg": mgr.theme.lightBg,
                                        "--theme-border": mgr.theme.border,
                                        "--theme-badge-bg": mgr.theme.badgeBg,
                                    } as React.CSSProperties
                                }
                            >
                                <div className={styles.managerBlockHeader}>
                                    <div className={styles.managerHeaderLeft}>
                                        <div className={styles.managerBlockIcon}>{mgr.icon}</div>
                                        <div className={styles.managerBlockTitleGroup}>
                                            <span className={styles.managerBlockIndexBadge}>
                                                Module 0{mIndex + 1}
                                            </span>
                                            <h3 className={styles.managerBlockTitle}>{mgr.title}</h3>
                                            <p className={styles.managerBlockTagline}>{mgr.tagline}</p>
                                        </div>
                                    </div>

                                    <div className={styles.managerHeaderRight}>
                                        <span className={styles.managerCountBadge}>
                                            <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
                                                <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                            </svg>
                                            {mgr.features.length} Specialized Sub-Modules
                                        </span>
                                        <div className={styles.capabilitiesRow}>
                                            {mgr.capabilities.map((cap, cIdx) => (
                                                <span key={cIdx} className={styles.capabilityPill}>
                                                    <span>•</span>
                                                    <span>{cap}</span>
                                                </span>
                                            ))}
                                        </div>
                                    </div>
                                </div>

                                {/* Sub-Features Grid for this Manager */}
                                <div className={styles.subFeaturesGrid}>
                                    {mgr.features.map((feature) => (
                                        <div key={feature.name} className={styles.subFeatureCard}>
                                            <div className={styles.subCardTop}>
                                                <span className={styles.subCardCodeBadge}>{feature.code}</span>
                                                <div className={styles.subCardIconMini}>{mgr.icon}</div>
                                            </div>

                                            <h4 className={styles.subCardTitle}>{feature.name}</h4>
                                            <p className={styles.subCardDesc}>{feature.description}</p>

                                            <ul className={styles.subCardHighlightsList}>
                                                {feature.highlights.map((h, hIdx) => (
                                                    <li key={hIdx} className={styles.subCardHighlightItem}>
                                                        <div className={styles.subCheckIconWrap}>
                                                            <svg width="10" height="10" viewBox="0 0 16 16" fill="none">
                                                                <path
                                                                    d="M13.3 4.3L6.5 11.1L2.7 7.3"
                                                                    stroke="currentColor"
                                                                    strokeWidth="2.4"
                                                                    strokeLinecap="round"
                                                                    strokeLinejoin="round"
                                                                />
                                                            </svg>
                                                        </div>
                                                        <span>{h}</span>
                                                    </li>
                                                ))}
                                            </ul>

                                            <div className={styles.subCardFooter}>
                                                <span className={styles.subOperationalPill}>
                                                    {feature.operationalPill}
                                                </span>
                                                <span className={styles.subLivePreviewNote}>
                                                    <span className={styles.liveNoteDot} />
                                                    <span>Live Sync</span>
                                                </span>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* 4. VISUAL DEEP DIVE SHOWCASE (Using Generated Matching Assets) */}
            <section className={styles.deepDiveSection}>
                <div className={styles.container}>
                    {/* Showcase 1: Retail Operations & POS Management */}
                    <div className={styles.showcaseRow}>
                        <div className={styles.showcaseText}>
                            <span className={styles.showcaseBadge}>OMNICHANNEL COMMAND</span>
                            <h2 className={styles.showcaseTitle}>
                                Unified Point of Sale &amp; Real-Time Intelligence
                            </h2>
                            <p className={styles.showcaseDesc}>
                                Deliver flawless customer checkouts in seconds while tracking margins, employee sales quotas,
                                and cash drawer floats with microscopic accuracy.
                            </p>
                            <ul className={styles.showcaseKeyPoints}>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Instant barcode and QR lookup for rapid billing without clerk lookup delays</span>
                                </li>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Automatic margin calculation, GST compliance slabs, and multi-tender splits</span>
                                </li>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Immediate customer loyalty points accrual and instant coupon voucher redemption</span>
                                </li>
                            </ul>
                            <Link href="/contact" className={styles.primaryBtn}>
                                Schedule POS Demo
                            </Link>
                        </div>
                        <div className={styles.showcaseImageCard}>
                            <Image
                                src="/retail_banner.jpg"
                                alt="Modern Retail Dashboard with Real Time Analytics"
                                width={620}
                                height={380}
                                className={styles.showcaseImg}
                            />
                        </div>
                    </div>

                    {/* Showcase 2: Warehouse & Stock Transfer Control */}
                    <div className={`${styles.showcaseRow} ${styles.showcaseRowReverse}`}>
                        <div className={styles.showcaseText}>
                            <span className={styles.showcaseBadge}>CENTRAL DEPOT &amp; INVENTORY</span>
                            <h2 className={styles.showcaseTitle}>
                                Automated Stock Transfers &amp; Batch Barcode Scanning
                            </h2>
                            <p className={styles.showcaseDesc}>
                                Eliminate inventory shrinkage and stock-outs forever. RetailNext tracks every single item
                                from supplier purchase orders and warehouse racking down to store-level shelf transfers.
                            </p>
                            <ul className={styles.showcaseKeyPoints}>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Inter-store stock transfer tracking with real-time transit &amp; dispatch states</span>
                                </li>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Batch-level expiry dates and FIFO automated rotation preventing dead inventory</span>
                                </li>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Thermal barcode sticker printing for easy batch inwarding and shelf labeling</span>
                                </li>
                            </ul>
                            <Link href="/contact" className={styles.primaryBtn}>
                                Explore Inventory Suite
                            </Link>
                        </div>
                        <div className={styles.showcaseImageCard}>
                            <Image
                                src="/retail_inventory.jpg"
                                alt="Warehouse Stock Management and Barcode Scanning"
                                width={620}
                                height={380}
                                className={styles.showcaseImg}
                            />
                        </div>
                    </div>
                </div>
            </section>

            {/* 5. FREQUENTLY ASKED QUESTIONS */}
            <section className={styles.faqSection}>
                <div className={styles.container}>
                    <div className={styles.sectionHeader}>
                        <span className={styles.sectionBadge}>FREQUENTLY ASKED QUESTIONS</span>
                        <h2 className={styles.sectionTitle}>Everything You Need to Know</h2>
                        <p className={styles.sectionSubtitle}>
                            Got questions regarding setup, hardware compatibility, or migration? We have answers.
                        </p>
                    </div>

                    <div className={styles.faqList}>
                        {faqs.map((faq, index) => {
                            const isOpen = openFaq === index;
                            return (
                                <div key={index} className={styles.faqItem}>
                                    <button
                                        type="button"
                                        onClick={() => toggleFaq(index)}
                                        className={styles.faqTrigger}
                                        aria-expanded={isOpen}
                                    >
                                        <span>{faq.q}</span>
                                        <svg
                                            className={`${styles.faqChevron} ${isOpen ? styles.faqChevronOpen : ""}`}
                                            viewBox="0 0 24 24"
                                            fill="none"
                                            stroke="currentColor"
                                            strokeWidth="2"
                                            strokeLinecap="round"
                                            strokeLinejoin="round"
                                        >
                                            <polyline points="6 9 12 15 18 9" />
                                        </svg>
                                    </button>
                                    {isOpen && <div className={styles.faqAnswer}>{faq.a}</div>}
                                </div>
                            );
                        })}
                    </div>
                </div>
            </section>

            {/* 6. BOTTOM CTA BANNER */}
            <section className={styles.ctaBannerSection}>
                <div className={styles.container}>
                    <div className={styles.bannerCard}>
                        <span className={styles.bannerBadge}>GET STARTED TODAY</span>
                        <h2 className={styles.bannerHeading}>Transform Your Retail Store with RetailNext</h2>
                        <p className={styles.bannerDesc}>
                            Join leading supermarkets, fashion outlets, and retail brands simplifying checkout,
                            optimizing multi-store inventory, and boosting profitability.
                        </p>
                        <div className={styles.bannerButtons}>
                            <Link href="/contact" className={styles.bannerBtnPrimary}>
                                Request Free Onsite Demo
                            </Link>
                            <Link href="/contact" className={styles.bannerBtnOutline}>
                                Talk to Retail Specialist
                            </Link>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    );
}
