"use client";

import React, { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import styles from "./retailnext.module.css";

interface SubFeature {
    name: string;
    description: string;
    highlights: string[];
}

interface ManagerModule {
    id: string;
    title: string;
    shortTitle: string;
    tagline: string;
    icon: React.ReactNode;
    features: SubFeature[];
}

export default function RetailNextPage() {
    const [activeTab, setActiveTab] = useState<string>("sales-manager");
    const [openFaq, setOpenFaq] = useState<number | null>(0);

    const toggleFaq = (index: number) => {
        setOpenFaq(openFaq === index ? null : index);
    };

    const managersData: ManagerModule[] = [
        {
            id: "sales-manager",
            title: "Sales Manager",
            shortTitle: "Sales",
            tagline: "Track revenue streams, cashier quotas, and counter registers in real time.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="18" y1="20" x2="18" y2="10" />
                    <line x1="12" y1="20" x2="12" y2="4" />
                    <line x1="6" y1="20" x2="6" y2="14" />
                </svg>
            ),
            features: [
                {
                    name: "Sales",
                    description: "Complete sales journal capturing every billed transaction across all retail outlets. Monitor real-time gross totals, net profit margins, taxes, and payment mode breakdowns.",
                    highlights: [
                        "Real-time transaction log & invoice reprints",
                        "Cash, UPI, Credit Card, and Store Credit breakdown",
                        "Tax (GST) summaries & margin computations",
                        "Instant export to Excel and PDF formats"
                    ]
                },
                {
                    name: "Employee Sales",
                    description: "Granular attribution of revenue generated by individual sales associates and counter cashiers. Measure employee contribution, targets, and sales commission incentives.",
                    highlights: [
                        "Individual staff sales targets & achievements",
                        "Automated commission calculation rules",
                        "Leaderboards to motivate peak counter performance",
                        "Audit cashier-level item discounts and overrides"
                    ]
                },
                {
                    name: "Counter Sales",
                    description: "End-to-end POS counter register reconciliation. Manage shift openings, cash drawer till floats, midday cash drops, and end-of-day X/Z shift closure reports.",
                    highlights: [
                        "Shift opening & closing float declarations",
                        "Physical drawer vs system cash discrepancy alerts",
                        "Detailed X-Report & Z-Report generation",
                        "Multi-counter load distribution tracking"
                    ]
                }
            ]
        },
        {
            id: "product-manager",
            title: "Product Manager",
            shortTitle: "Products",
            tagline: "Centralized catalog management with variations, barcode printing, and pricing tiers.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
                    <polyline points="3.27 6.96 12 12.01 20.73 6.96" />
                    <line x1="12" y1="22.08" x2="12" y2="12" />
                </svg>
            ),
            features: [
                {
                    name: "Categories",
                    description: "Structured multi-level categorization tree for departments, sub-categories, and brands. Enforces automated GST tax slab rules and quick-filter buttons on POS screens.",
                    highlights: [
                        "Parent-child category hierarchies",
                        "Tax slabs & HSN mappings at category level",
                        "POS quick-touch tile groupings",
                        "Departmental sales margin reporting"
                    ]
                },
                {
                    name: "Variations",
                    description: "Advanced variation matrix manager for retail products with diverse sizes, colors, fabric types, weights, and bundle options under a single master parent product.",
                    highlights: [
                        "Size, color, weight, and style matrix builder",
                        "Independent SKU & Barcode per variant",
                        "Differential pricing per size or edition",
                        "Variant-level inventory allocation"
                    ]
                },
                {
                    name: "Products",
                    description: "Universal master catalog of all retail items. Configure SKU codes, item descriptions, purchase costs, MRP, wholesale rate, batch settings, and reorder limits.",
                    highlights: [
                        "Unified SKU, HSN/SAC code, and brand data",
                        "Cost price vs MRP margin configuration",
                        "Minimum reorder alert threshold settings",
                        "Bulk product import/export via CSV templates"
                    ]
                },
                {
                    name: "Barcode Generator",
                    description: "Integrated in-house barcode and QR label generator. Design custom sticker layouts with product name, price, expiry, and batch number, then print directly to thermal label rolls.",
                    highlights: [
                        "Supports EAN-13, Code-128, and QR Code formats",
                        "Customizable label dimensions (single & multi-column)",
                        "One-click batch sticker printing for new inwards",
                        "Seamless compatibility with Zebra, TSC, and TVS printers"
                    ]
                }
            ]
        },
        {
            id: "return-exchange-manager",
            title: "Return & Exchange Manager",
            shortTitle: "Return & Exchange",
            tagline: "Hassle-free counter returns, condition verification, and automated customer refunds.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <polyline points="1 4 1 10 7 10" />
                    <polyline points="23 20 23 14 17 14" />
                    <path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 0 1 3.51 15" />
                </svg>
            ),
            features: [
                {
                    name: "Returns",
                    description: "Lightning-fast return handling at the checkout counter. Lookup past bills by invoice number or mobile, verify purchase eligibility, and issue cash refunds or store credits.",
                    highlights: [
                        "Scan invoice barcode to pull complete bill data",
                        "Item condition audit (resellable vs damaged/defective)",
                        "Issue Store Credit Notes or direct cash/UPI refunds",
                        "Strict supervisor override approvals for safety"
                    ]
                },
                {
                    name: "Exchanges",
                    description: "Process in-line product exchanges in a single transaction. Swap sizes, colors, or switch to a different product while instantly computing price adjustments.",
                    highlights: [
                        "Single-receipt swap (Return item + New purchase)",
                        "Instant debit or credit balance reconciliation",
                        "Zero manual calculation errors for counter clerks",
                        "Automatic inventory replenishment for good returns"
                    ]
                }
            ]
        },
        {
            id: "stock-manager",
            title: "Stock Manager",
            shortTitle: "Stock",
            tagline: "Complete multi-warehouse inventory control, batch-tracking, and inter-store stock transfers.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="2" y="7" width="20" height="14" rx="2" ry="2" />
                    <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
                </svg>
            ),
            features: [
                {
                    name: "Warehouse",
                    description: "Manage central warehousing, regional distribution hubs, and backroom storage. Define rack, aisle, and bin locations for optimized product pick-and-pack operations.",
                    highlights: [
                        "Multi-warehouse storage location hierarchy",
                        "Rack, shelf, and bin location tagging",
                        "Goods Received Notes (GRN) inward workflows",
                        "Damaged / expired quarantine inventory zones"
                    ]
                },
                {
                    name: "Stock",
                    description: "Live real-time visibility into quantities on hand, reserved orders, and inventory in-transit. Automated FIFO batch evaluation, expiry alerts, and stock adjustments.",
                    highlights: [
                        "Live stock counts synchronized across all stores",
                        "Batch number & expiration date tracking",
                        "Physical stock audit & cycle counting tools",
                        "Automated low-stock reorder triggers"
                    ]
                },
                {
                    name: "Stock Transfers",
                    description: "Orchestrate internal stock transfer orders (STO) between warehouses and retail stores or across store branches. Track transit milestones and verify received quantities.",
                    highlights: [
                        "Store-to-Store and Warehouse-to-Store requests",
                        "Dispatch, in-transit, and receiving status states",
                        "Discrepancy and damaged in-transit loss reporting",
                        "One-click receiving with barcode scanning validation"
                    ]
                }
            ]
        },
        {
            id: "customer-manager",
            title: "Customer Manager",
            shortTitle: "Customer",
            tagline: "Comprehensive customer relationship management, loyalty rewards, and credit ledger.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" />
                    <circle cx="9" cy="7" r="4" />
                    <path d="M23 21v-2a4 4 0 0 0-3-3.87" />
                    <path d="M16 3.13a4 4 0 0 1 0 7.75" />
                </svg>
            ),
            features: [
                {
                    name: "Customer",
                    description: "Master directory of retail shoppers and wholesale B2B clients. Group customers into membership tiers, analyze purchase behavior, and track store credit accounts.",
                    highlights: [
                        "Centralized contact database with GSTIN support for B2B",
                        "Loyalty points accumulation and redemption engine",
                        "Credit balance limit setting & payment dues reminders",
                        "Export customer segments for targeted SMS campaigns"
                    ]
                },
                {
                    name: "Individual Customer",
                    description: "360-degree customer profile view. Review chronological purchase timelines, average basket size, favorite categories, pending dues, and customized notes.",
                    highlights: [
                        "Complete itemized purchase history per customer",
                        "Outstanding credit balance ledger with payment history",
                        "Special discounts and exclusive custom pricing",
                        "Birthday, anniversary, and preference alerts"
                    ]
                }
            ]
        },
        {
            id: "discount-manager",
            title: "Discount Manager",
            shortTitle: "Discounts",
            tagline: "Dynamic promotional coupon engine, order discounts, and targeted customer perks.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="19" y1="5" x2="5" y2="19" />
                    <circle cx="6.5" cy="6.5" r="2.5" />
                    <circle cx="17.5" cy="17.5" r="2.5" />
                </svg>
            ),
            features: [
                {
                    name: "Order Coupons",
                    description: "Create cart-level promotional coupons for festive sales, minimum spending tiers, and flat or percentage reductions applied seamlessly at checkout.",
                    highlights: [
                        "Minimum cart value prerequisites and caps",
                        "Flat currency discount or percentage discount rules",
                        "Validity period scheduling with auto-expiry",
                        "Usage limits per coupon code"
                    ]
                },
                {
                    name: "Product Coupons",
                    description: "Run targeted promotional pricing on specific items, brands, or seasonal merchandise. Ideal for flash clearances, slow-moving items, or brand partnerships.",
                    highlights: [
                        "Category-wide and SKU-specific discount rules",
                        "Buy-One-Get-One (BOGO) combo deal support",
                        "Automatic discount deduction upon barcode scan",
                        "Margin-protection rules preventing negative margins"
                    ]
                },
                {
                    name: "Customer Coupons",
                    description: "Personalized vouchers tailored for individual VIP patrons, first-time shoppers, or win-back campaigns to re-engage inactive customers.",
                    highlights: [
                        "Unique single-use promo codes assigned to phones",
                        "Customer birthday & milestone rewards",
                        "Exclusive VIP customer tier promotions",
                        "Redemption tracking and conversion analytics"
                    ]
                }
            ]
        },
        {
            id: "vendors-manager",
            title: "Vendors Manager",
            shortTitle: "Vendors",
            tagline: "Supplier lifecycle management, automated Purchase Orders, invoice 3-way matching, and dues.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="4" y="2" width="16" height="20" rx="2" ry="2" />
                    <line x1="9" y1="22" x2="9" y2="2" />
                    <path d="M8 6h.01" />
                    <path d="M16 6h.01" />
                    <path d="M8 10h.01" />
                    <path d="M16 10h.01" />
                    <path d="M8 14h.01" />
                    <path d="M16 14h.01" />
                    <path d="M8 18h.01" />
                    <path d="M16 18h.01" />
                </svg>
            ),
            features: [
                {
                    name: "Vendors",
                    description: "Comprehensive vendor database recording business names, contact persons, tax registration (GSTIN), credit terms, bank details, and lead procurement times.",
                    highlights: [
                        "Supplier contact & compliance registry",
                        "Credit terms & credit period (30/60/90 days) tracking",
                        "Vendor ratings and fulfillment speed metrics",
                        "Catalog pricing agreements and negotiated rates"
                    ]
                },
                {
                    name: "Vendors Orders",
                    description: "End-to-end Purchase Order (PO) creation, automated order email dispatch, expected delivery scheduling, and supplier confirmation tracking.",
                    highlights: [
                        "Auto-generate PO from low-stock thresholds",
                        "Multi-level manager approval workflow",
                        "Tracking partial deliveries and pending shipments",
                        "Direct PDF PO generation for instant dispatch"
                    ]
                },
                {
                    name: "Vendors Invoices",
                    description: "Inward purchase bill logging with 3-way reconciliation (PO vs GRN Inward vs Vendor Bill). Accurately claim input tax credits and record landed freight costs.",
                    highlights: [
                        "3-way matching preventing supplier overbilling",
                        "Input Tax Credit (ITC) categorization",
                        "Landed cost calculation incorporating shipping & customs",
                        "Direct inventory auto-inward upon invoice approval"
                    ]
                },
                {
                    name: "Vendors Due",
                    description: "Accounts payable ledger providing real-time visibility into supplier outstanding payments, upcoming due dates, aging analysis, and partial settlements.",
                    highlights: [
                        "Payables aging schedule (0-30, 31-60, 60+ days)",
                        "Due date alert notifications avoiding late penalties",
                        "Cheque, NEFT/RTGS, and UPI settlement tracking",
                        "Consolidated vendor statement generation"
                    ]
                }
            ]
        },
        {
            id: "staff-manager",
            title: "Staff Manager",
            shortTitle: "Staff",
            tagline: "Role-based access control, cashier permission security, and sensitive operational guards.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                    <circle cx="12" cy="7" r="4" />
                </svg>
            ),
            features: [
                {
                    name: "Staff",
                    description: "Define staff roles and permissions with fine-grained security. Prevent unauthorized billing discounts, prohibit arbitrary price overrides, and protect sensitive financial reports.",
                    highlights: [
                        "Role-based permission sets (Cashier, Supervisor, Manager)",
                        "Passcode requirements for bill cancellation & refunds",
                        "Restrict access to profit margins and wholesale purchase rates",
                        "Detailed chronological audit logs of sensitive operations"
                    ]
                }
            ]
        },
        {
            id: "employee-manager",
            title: "Employee Manager",
            shortTitle: "Employee HR",
            tagline: "Integrated HR management, shift attendance, payroll processing, ID cards, and salary advances.",
            icon: (
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
                    <circle cx="11" cy="7" r="4" />
                    <polyline points="16 11 18 13 22 9" />
                </svg>
            ),
            features: [
                {
                    name: "Employees",
                    description: "Complete employee master directory holding personal identification, KYC documents, designated roles, emergency contacts, and assigned retail branch locations.",
                    highlights: [
                        "Comprehensive employee master profiles & documents",
                        "Branch assignment & shift roster allocation",
                        "Employment contracts & document uploads",
                        "Emergency contact registry"
                    ]
                },
                {
                    name: "Employee Attendance",
                    description: "Daily shift punch clocking with biometric terminal or PIN entry integration. Tracks punctual clock-ins, lunch breaks, overtime hours, and half-day calculations.",
                    highlights: [
                        "Biometric, RFID, or PIN-based counter clock-in",
                        "Overtime and late-punch calculation rules",
                        "Monthly attendance percentage overview",
                        "Shift swap requests and approvals"
                    ]
                },
                {
                    name: "Payroll",
                    description: "Automated monthly wage processing incorporating basic salary, attendance deductions, overtime pay, sales commissions, and statutory deductions.",
                    highlights: [
                        "One-click monthly salary sheet calculation",
                        "Automated inclusion of sales target commissions",
                        "Deduction for unpaid leaves and advances",
                        "Printable & downloadable digital payslips"
                    ]
                },
                {
                    name: "Id Cards",
                    description: "Generate and print professional employee identity cards featuring store branding, staff portrait photo, employee ID, and quick-login barcode or QR code.",
                    highlights: [
                        "Branded printable ID card templates",
                        "Quick-scan barcode for instant POS till logins",
                        "Staff security badges with role designations",
                        "Single-click batch printing"
                    ]
                },
                {
                    name: "Employee leaves",
                    description: "Structured leave management system with policy balances (Casual Leave, Sick Leave, Paid Time Off). Staff can apply for leave with quick manager approval workflows.",
                    highlights: [
                        "Leave quota configuration per employee type",
                        "Leave request submission & approval notifications",
                        "Real-time available leave balance ledger",
                        "Direct synchronization with monthly payroll computations"
                    ]
                },
                {
                    name: "Employee Advances",
                    description: "Record and manage employee salary advance loans. Configure monthly deduction installments that automatically link into monthly payroll generation.",
                    highlights: [
                        "Formal advance request recording and approvals",
                        "Custom installment repayment schedules",
                        "Automatic monthly payroll deduction linking",
                        "Remaining balance audit trail"
                    ]
                }
            ]
        }
    ];

    const currentManager = managersData.find((m) => m.id === activeTab) || managersData[0];

    const faqs = [
        {
            q: "Can RetailNext run across multiple retail branch stores simultaneously?",
            a: "Yes! RetailNext is architected from the ground up for multi-store chains. You can manage central inventory in a master warehouse, transfer stock between branch stores, and view centralized sales performance in real time from any device."
        },
        {
            q: "How does RetailNext handle high-traffic billing counters during peak hours?",
            a: "RetailNext features high-speed keyboard shortcuts, instant barcode scanning, hold-and-recall cart capabilities, and multi-tender split payments (Cash + UPI + Card) to ensure customer checkout takes less than 5 seconds per transaction."
        },
        {
            q: "Can I print customized barcode stickers for products without manufacturer barcodes?",
            a: "Absolutely. The built-in Barcode Generator allows you to design custom label layouts (incorporating your shop name, product name, MRP, selling price, and expiry date) and batch-print them directly onto thermal sticker rolls."
        },
        {
            q: "How are employee commissions and cashier registers audited?",
            a: "The Sales Manager and Employee Manager modules collaborate seamlessly. Every bill tracks the serving staff member, automatically calculating earned commissions, while Counter Sales reconciles physical cash drawer balances against system totals at shift close."
        },
        {
            q: "Does RetailNext offer role-based access control for cashiers vs store managers?",
            a: "Yes. The Staff Manager provides granular permission toggles. Cashiers can be restricted from viewing purchase costs, profit margins, or executing bill cancellations without a supervisor PIN override."
        }
    ];

    return (
        <main className={styles.pageWrapper}>
            {/* 1. HERO SECTION */}
            <section className={styles.heroSection}>
                <div className={styles.container}>
                    <div className={styles.heroGrid}>
                        <div className={styles.heroContent}>
                            <span className={styles.badge}>RETAIL ERP &amp; POS SUITE</span>
                            <h1 className={styles.title}>
                                Modern Retail OS <br />
                                Built for <span className={styles.highlightText}>Speed &amp; Scale</span>
                            </h1>
                            <p className={styles.description}>
                                The complete cloud-ready retail operating system. From high-speed barcode checkout
                                and multi-warehouse stock replenishment to staff payroll and vendor management —
                                everything you need to run your retail chain flawlessly.
                            </p>

                            <div className={styles.ctaGroup}>
                                <Link href="/contact" className={styles.primaryBtn}>
                                    Book a Live Demo
                                    <svg width="15" height="15" viewBox="0 0 16 16" fill="none">
                                        <path d="M6 3L11 8L6 13" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                </Link>
                                <a href="#managers-suite" className={styles.secondaryBtn}>
                                    Explore All Modules
                                    <svg width="15" height="15" viewBox="0 0 16 16" fill="none">
                                        <path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                </a>
                            </div>

                            <div className={styles.statsBar}>
                                <div className={styles.statItem}>
                                    <span className={styles.statValue}>&lt; 5s</span>
                                    <span className={styles.statLabel}>Billing Speed</span>
                                </div>
                                <div className={styles.statItem}>
                                    <span className={styles.statValue}>100%</span>
                                    <span className={styles.statLabel}>Stock Accuracy</span>
                                </div>
                                <div className={styles.statItem}>
                                    <span className={styles.statValue}>Multi-Store</span>
                                    <span className={styles.statLabel}>Chain Ready</span>
                                </div>
                                <div className={styles.statItem}>
                                    <span className={styles.statValue}>All-in-One</span>
                                    <span className={styles.statLabel}>POS + HR + ERP</span>
                                </div>
                            </div>
                        </div>

                        <div className={styles.heroVisualWrapper}>
                            <Image
                                src="/retail.png"
                                alt="RetailNext POS Billing and Supermarket Terminal"
                                width={680}
                                height={440}
                                className={styles.heroImage}
                                priority
                            />
                            <div className={styles.floatingTag}>
                                <span className={styles.liveDot} />
                                <span>Real-time POS &amp; Inventory Cloud Sync</span>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* 2. OPERATIONAL PILLARS (Top Navigation Highlights) */}
            <section className={styles.pillarsSection}>
                <div className={styles.container}>
                    <div className={styles.sectionHeader}>
                        <span className={styles.sectionBadge}>CORE PILLARS</span>
                        <h2 className={styles.sectionTitle}>Built for High-Velocity Retail Operations</h2>
                        <p className={styles.sectionSubtitle}>
                            Three interconnected pillars that keep your checkout counters moving fast,
                            your shelves stocked, and your management in total command.
                        </p>
                    </div>

                    <div className={styles.pillarsGrid}>
                        {/* Pillar 1: POS Billing */}
                        <div className={styles.pillarCard}>
                            <div className={styles.pillarIconWrap}>
                                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <rect x="2" y="3" width="20" height="14" rx="2" ry="2" />
                                    <line x1="8" y1="21" x2="16" y2="21" />
                                    <line x1="12" y1="17" x2="12" y2="21" />
                                </svg>
                            </div>
                            <h3 className={styles.pillarTitle}>High-Speed POS Billing</h3>
                            <p className={styles.pillarDesc}>
                                Lightning checkout designed for peak rushes with keyboard shortcuts, instant barcode lookup, and split payments.
                            </p>
                            <ul className={styles.pillarFeatureList}>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Barcode, QR &amp; touch item selection</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Hold &amp; recall carts without line delays</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Multi-tender payments: Cash, UPI, Card, Credit</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Thermal receipt and WhatsApp invoice sharing</span>
                                </li>
                            </ul>
                        </div>

                        {/* Pillar 2: Real-time Dashboard */}
                        <div className={styles.pillarCard}>
                            <div className={styles.pillarIconWrap}>
                                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <rect x="3" y="3" width="7" height="9" />
                                    <rect x="14" y="3" width="7" height="5" />
                                    <rect x="14" y="12" width="7" height="9" />
                                    <rect x="3" y="16" width="7" height="5" />
                                </svg>
                            </div>
                            <h3 className={styles.pillarTitle}>Real-Time Executive Dashboard</h3>
                            <p className={styles.pillarDesc}>
                                Live operational intelligence. Track daily turnover, margins, hourly footfall, and low-inventory alerts.
                            </p>
                            <ul className={styles.pillarFeatureList}>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Today’s gross sales, tax &amp; net margins</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Top-selling SKU velocity &amp; category trends</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Automated low stock and expiry warnings</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Mobile manager dashboard on any device</span>
                                </li>
                            </ul>
                        </div>

                        {/* Pillar 3: Multi-Store Control */}
                        <div className={styles.pillarCard}>
                            <div className={styles.pillarIconWrap}>
                                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
                                    <polyline points="9 22 9 12 15 12 15 22" />
                                </svg>
                            </div>
                            <h3 className={styles.pillarTitle}>Multi-Store Network (Stores)</h3>
                            <p className={styles.pillarDesc}>
                                Unify all physical stores, outlet counters, and depots under a central cloud control room with zero sync latency.
                            </p>
                            <ul className={styles.pillarFeatureList}>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Multi-branch master inventory synchronization</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Outlet-specific pricing and promotional slabs</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Inter-store stock transfer management</span>
                                </li>
                                <li className={styles.pillarFeatureItem}>
                                    <span className={styles.bulletDot} />
                                    <span>Consolidated multi-branch P&amp;L reporting</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </section>

            {/* 3. MANAGER-WISE FEATURE SUITE */}
            <section className={styles.managersSection} id="managers-suite">
                <div className={styles.container}>
                    <div className={styles.sectionHeader}>
                        <span className={styles.sectionBadge}>COMPLETE SYSTEM ARCHITECTURE</span>
                        <h2 className={styles.sectionTitle}>Manager-Wise Module Deep Dive</h2>
                        <p className={styles.sectionSubtitle}>
                            Explore how each specialized manager module inside RetailNext automates your store operations
                            from procurement to payroll.
                        </p>
                    </div>

                    {/* Interactive Tab Navigation */}
                    <div className={styles.managerTabsRow}>
                        {managersData.map((mgr) => {
                            const isActive = mgr.id === activeTab;
                            return (
                                <button
                                    key={mgr.id}
                                    type="button"
                                    onClick={() => setActiveTab(mgr.id)}
                                    className={`${styles.tabButton} ${isActive ? styles.activeTabButton : ""}`}
                                >
                                    {mgr.icon}
                                    <span>{mgr.title}</span>
                                </button>
                            );
                        })}
                    </div>

                    {/* Active Manager Display Card */}
                    <div className={styles.managerDisplayCard}>
                        <div className={styles.managerHeader}>
                            <div className={styles.managerMeta}>
                                <div className={styles.managerLargeIcon}>{currentManager.icon}</div>
                                <div>
                                    <h3 className={styles.managerTitle}>{currentManager.title}</h3>
                                    <p className={styles.managerTagline}>{currentManager.tagline}</p>
                                </div>
                            </div>
                            <span className={styles.managerFeatureCountBadge}>
                                <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
                                    <circle cx="8" cy="8" r="7" stroke="currentColor" strokeWidth="1.5" />
                                    <path d="M8 5v6M5 8h6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                                </svg>
                                {currentManager.features.length} Specialized Sub-Modules
                            </span>
                        </div>

                        {/* Feature Cards Grid */}
                        <div className={styles.featuresGrid}>
                            {currentManager.features.map((feature, fIndex) => (
                                <div key={feature.name} className={styles.featureCard}>
                                    <div className={styles.featureCardHeader}>
                                        <span className={styles.featureNumber}>0{fIndex + 1}</span>
                                        <h4 className={styles.featureCardTitle}>{feature.name}</h4>
                                    </div>
                                    <p className={styles.featureCardDesc}>{feature.description}</p>

                                    <ul className={styles.featureHighlightsList}>
                                        {feature.highlights.map((h, hIndex) => (
                                            <li key={hIndex} className={styles.featureHighlightItem}>
                                                <svg
                                                    className={styles.checkIcon}
                                                    width="13"
                                                    height="13"
                                                    viewBox="0 0 16 16"
                                                    fill="none"
                                                >
                                                    <path
                                                        d="M13.3 4.3L6.5 11.1L2.7 7.3"
                                                        stroke="currentColor"
                                                        strokeWidth="2.2"
                                                        strokeLinecap="round"
                                                        strokeLinejoin="round"
                                                    />
                                                </svg>
                                                <span>{h}</span>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </section>

            {/* 4. VISUAL DEEP DIVE SHOWCASE (Using Generated Matching Assets) */}
            <section className={styles.deepDiveSection}>
                <div className={styles.container}>
                    {/* Showcase 1: Retail Operations & POS Management */}
                    <div className={styles.showcaseRow}>
                        <div className={styles.showcaseText}>
                            <span className={styles.showcaseBadge}>OMNICHANNEL COMMAND</span>
                            <h2 className={styles.showcaseTitle}>
                                Unified Point of Sale &amp; Real-Time Intelligence
                            </h2>
                            <p className={styles.showcaseDesc}>
                                Deliver flawless customer checkouts in seconds while tracking margins, employee sales quotas,
                                and cash drawer floats with microscopic accuracy.
                            </p>
                            <ul className={styles.showcaseKeyPoints}>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Instant barcode and QR lookup for rapid billing without clerk lookup delays</span>
                                </li>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Automatic margin calculation, GST compliance slabs, and multi-tender splits</span>
                                </li>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Immediate customer loyalty points accrual and instant coupon voucher redemption</span>
                                </li>
                            </ul>
                            <Link href="/contact" className={styles.primaryBtn}>
                                Schedule POS Demo
                            </Link>
                        </div>
                        <div className={styles.showcaseImageCard}>
                            <Image
                                src="/retail_banner.jpg"
                                alt="Modern Retail Dashboard with Real Time Analytics"
                                width={620}
                                height={380}
                                className={styles.showcaseImg}
                            />
                        </div>
                    </div>

                    {/* Showcase 2: Warehouse & Stock Transfer Control */}
                    <div className={`${styles.showcaseRow} ${styles.showcaseRowReverse}`}>
                        <div className={styles.showcaseText}>
                            <span className={styles.showcaseBadge}>CENTRAL DEPOT &amp; INVENTORY</span>
                            <h2 className={styles.showcaseTitle}>
                                Automated Stock Transfers &amp; Batch Barcode Scanning
                            </h2>
                            <p className={styles.showcaseDesc}>
                                Eliminate inventory shrinkage and stock-outs forever. RetailNext tracks every single item
                                from supplier purchase orders and warehouse racking down to store-level shelf transfers.
                            </p>
                            <ul className={styles.showcaseKeyPoints}>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Inter-store stock transfer tracking with real-time transit &amp; dispatch states</span>
                                </li>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Batch-level expiry dates and FIFO automated rotation preventing dead inventory</span>
                                </li>
                                <li className={styles.showcaseKeyPointItem}>
                                    <svg className={styles.keyPointCheck} width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path d="M13.3 4.3L6.5 11.1L2.7 7.3" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
                                    </svg>
                                    <span>Thermal barcode sticker printing for easy batch inwarding and shelf labeling</span>
                                </li>
                            </ul>
                            <Link href="/contact" className={styles.primaryBtn}>
                                Explore Inventory Suite
                            </Link>
                        </div>
                        <div className={styles.showcaseImageCard}>
                            <Image
                                src="/retail_inventory.jpg"
                                alt="Warehouse Stock Management and Barcode Scanning"
                                width={620}
                                height={380}
                                className={styles.showcaseImg}
                            />
                        </div>
                    </div>
                </div>
            </section>

            {/* 5. FREQUENTLY ASKED QUESTIONS */}
            <section className={styles.faqSection}>
                <div className={styles.container}>
                    <div className={styles.sectionHeader}>
                        <span className={styles.sectionBadge}>FREQUENTLY ASKED QUESTIONS</span>
                        <h2 className={styles.sectionTitle}>Everything You Need to Know</h2>
                        <p className={styles.sectionSubtitle}>
                            Got questions regarding setup, hardware compatibility, or migration? We have answers.
                        </p>
                    </div>

                    <div className={styles.faqList}>
                        {faqs.map((faq, index) => {
                            const isOpen = openFaq === index;
                            return (
                                <div key={index} className={styles.faqItem}>
                                    <button
                                        type="button"
                                        onClick={() => toggleFaq(index)}
                                        className={styles.faqTrigger}
                                        aria-expanded={isOpen}
                                    >
                                        <span>{faq.q}</span>
                                        <svg
                                            className={`${styles.faqChevron} ${isOpen ? styles.faqChevronOpen : ""}`}
                                            viewBox="0 0 24 24"
                                            fill="none"
                                            stroke="currentColor"
                                            strokeWidth="2"
                                            strokeLinecap="round"
                                            strokeLinejoin="round"
                                        >
                                            <polyline points="6 9 12 15 18 9" />
                                        </svg>
                                    </button>
                                    {isOpen && <div className={styles.faqAnswer}>{faq.a}</div>}
                                </div>
                            );
                        })}
                    </div>
                </div>
            </section>

            {/* 6. BOTTOM CTA BANNER */}
            <section className={styles.ctaBannerSection}>
                <div className={styles.container}>
                    <div className={styles.bannerCard}>
                        <span className={styles.bannerBadge}>GET STARTED TODAY</span>
                        <h2 className={styles.bannerHeading}>Transform Your Retail Store with RetailNext</h2>
                        <p className={styles.bannerDesc}>
                            Join leading supermarkets, fashion outlets, and retail brands simplifying checkout,
                            optimizing multi-store inventory, and boosting profitability.
                        </p>
                        <div className={styles.bannerButtons}>
                            <Link href="/contact" className={styles.bannerBtnPrimary}>
                                Request Free Onsite Demo
                            </Link>
                            <Link href="/contact" className={styles.bannerBtnOutline}>
                                Talk to Retail Specialist
                            </Link>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    );
}
